### ISSUE TITLE
Server hub crashed

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#620]
[server-hub] [2024-04-14 04:08:30] error: Uncaught (in promise) TypeError: error sending request for url (https://nyc3.digitaloceanspaces.com/jordan/spellmasons-logs.json): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
[server-hub] [2024-04-14 04:08:30]     const res = await doRequest({
[server-hub] [2024-04-14 04:08:30]                 ^
[server-hub] [2024-04-14 04:08:30]     at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
[server-hub] [2024-04-14 04:08:30]     at async fetch (deno:ext/fetch/26_fetch.js:491:9)
[server-hub] [2024-04-14 04:08:30]     at async S3Bucket.getObject (https://deno.land/x/s3@0.5.0/src/bucket.ts:196:17)
[server-hub] [2024-04-14 04:08:30]     at async getObjectInBucket (file:///app/app/s3.ts:26:16)
[server-hub] [2024-04-14 04:08:30]     at async file:///app/app/main.ts:51:20

**Comment by jdoleary** [comment]
[server-hub] [2024-04-17 21:30:43] error: Uncaught (in promise) TypeError: error sending request for url (https://nyc3.digitaloceanspaces.com/jordan/spellmasons-logs.json): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
[server-hub] [2024-04-17 21:30:43]     const res = await doRequest({
[server-hub] [2024-04-17 21:30:43]                 ^
[server-hub] [2024-04-17 21:30:43]     at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
[server-hub] [2024-04-17 21:30:43]     at async fetch (deno:ext/fetch/26_fetch.js:491:9)
[server-hub] [2024-04-17 21:30:43]     at async S3Bucket.getObject (https://deno.land/x/s3@0.5.0/src/bucket.ts:196:17)
[server-hub] [2024-04-17 21:30:43]     at async getObjectInBucket (file:///app/app/s3.ts:26:16)
[server-hub] [2024-04-17 21:30:43]     at async file:///app/app/main.ts:51:20

**Comment by jdoleary** [comment]
Fixed
