### ISSUE TITLE
Server hub issue

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#661]
updateServerInformation failed TypeError: error sending request for url (https://www.spellmasons.com/serverList.json): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
[server-hub] [2024-04-25 10:46:37]     at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
[server-hub] [2024-04-25 10:46:37]     at async fetch (deno:ext/fetch/26_fetch.js:491:9)
[server-hub] [2024-04-25 10:46:37]     at async updateServerInformation (file:///app/app/main.ts:219:18)
[server-hub] [2024-04-25 10:51:17]      Updating server information
[server-hub] [2024-04-25 10:51:37] updateServerInformation failed TypeError: error sending request for url (https://www.spellmasons.com/serverList.json): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
[server-hub] [2024-04-25 10:51:37]     at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
[server-hub] [2024-04-25 10:51:37]     at async fetch (deno:ext/fetch/26_fetch.js:491:9)
[server-hub] [2024-04-25 10:51:37]     at async updateServerInformation (file:///app/app/main.ts:219:18)
[server-hub] [2024-04-25 10:56:17]      Updating server information
[server-hub] [2024-04-25 10:56:37] updateServerInformation failed TypeError: error sending request for url (https://www.spellmasons.com/serverList.json): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
[server-hub] [2024-04-25 10:56:37]     at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
[server-hub] [2024-04-25 10:56:37]     at async fetch (deno:ext/fetch/26_fetch.js:491:9)
[server-hub] [2024-04-25 10:56:37]     at async updateServerInformation (file:///app/app/main.ts:219:18)
[server-hub] [2024-04-25 11:01:17]      Updating server information
[server-hub] [2024-04-25 11:01:37] updateServerInformation failed TypeError: error sending request for url (https://www.spellmasons.com/serverList.json): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
[server-hub] [2024-04-25 11:01:37]     at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
[server-hub] [2024-04-25 11:01:37]     at async fetch (deno:ext/fetch/26_fetch.js:491:9)
[server-hub] [2024-04-25 11:01:37]     at async updateServerInformation (file:///app/app/main.ts:219:18)

**Comment by jdoleary** [comment]
Can't reproduce, it should've still served the serverList that it had

**Comment by jdoleary** [comment]
It looks like the server hub keeps restarting, I need to disable the logging for now and just let it host the servers

**Comment by jdoleary** [comment]
I've pushed an update to the server hub, now I need to verify that it stops restarting all the time
![image](https://github.com/jdoleary/Spellmasons/assets/6413317/3e30dbe8-95d3-48e1-90e2-99ec96aadde7)

**Comment by jdoleary** [comment]
Fixed
